Update CI workflow to also check the docs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,3 +42,24 @@ jobs:
           go-version-file: go.mod
       - name: Build and Check
         run: make plugin-check
+  docs:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v6
+      - name: Setup Go Environment
+        uses: actions/setup-go@v6
+        with:
+          go-version-file: go.mod
+      - name: Generate Docs
+        run: make docs
+      - name: Check Docs
+        run: |
+          if [[ -z "$(git status -s)" ]]; then
+            echo "OK"
+          else
+            echo "Docs have been updated, but the compiled docs have not been committed."
+            echo "Run 'make docs', and commit the result to resolve this error."
+            exit 1
+          fi
